"""SFT fine-tuning of Qwen3-8B on rationalization traces using Tinker.

Loads SFT data from data/traces/*_sft.jsonl (generated by generate_traces.py),
formats as chat conversations, and trains with LoRA via Tinker.

Usage:
    # Install tinker-cookbook first:
    #   pip install tinker-cookbook

    # Pilot (1,000 traces)
    python scripts/tinker_sft.py --data data/traces/traces_deepseek_r1_n1000_*_sft.jsonl

    # Full training set
    python scripts/tinker_sft.py --data data/traces/traces_deepseek_r1_*_sft.jsonl

    # Resume from checkpoint
    python scripts/tinker_sft.py --data ... --resume

Requires:
    pip install tinker-cookbook
    export TINKER_API_KEY=...  (or configured via tinker CLI)
"""

from __future__ import annotations

import json
import logging
import time
from pathlib import Path

import chz
import tinker

from tinker_cookbook import checkpoint_utils, model_info, renderers
from tinker_cookbook.supervised.common import compute_mean_nll
from tinker_cookbook.supervised.data import conversation_to_datum
from tinker_cookbook.tokenizer_utils import get_tokenizer
from tinker_cookbook.utils import ml_log

logger = logging.getLogger(__name__)
logging.getLogger("httpx").setLevel(logging.WARN)

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# System prompt (same as evaluation — model sees this at both train & test)
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = (
    "You are an expert materials scientist. You will be given a multiple-choice "
    "question about ionic substitution in crystalline materials. Reason briefly "
    "about which substitution best meets the design goal, considering "
    "factors like ionic radius, electronegativity, charge balance, and known "
    "stability trends. Keep your reasoning concise (under 200 words). "
    'End your response with "Answer: (X)" where X is the letter of your chosen option.'
)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------


def load_sft_data(data_path: str) -> list[list[dict[str, str]]]:
    """Load SFT JSONL and convert to chat message format.

    Each line has {"input": question, "output": reasoning trace}.
    We format as: [system, user(input), assistant(output)].
    """
    conversations = []
    path = Path(data_path)

    if not path.exists():
        # Try glob pattern
        import glob
        files = sorted(glob.glob(data_path))
        if not files:
            raise FileNotFoundError(f"No files matching: {data_path}")
        path = Path(files[-1])  # Use most recent
        logger.info("Using data file: %s", path)

    with open(path) as f:
        for line in f:
            if not line.strip():
                continue
            item = json.loads(line)
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": item["input"]},
                {"role": "assistant", "content": item["output"]},
            ]
            conversations.append(messages)

    return conversations


# ---------------------------------------------------------------------------
# Training config
# ---------------------------------------------------------------------------

MODEL_NAME = "meta-llama/Llama-3.1-8B-Instruct"


@chz.chz
class Config:
    base_url: str | None = None
    log_path: str = str(PROJECT_ROOT / "runs" / "sft_llama_3p1_8b")
    data_path: str = ""
    batch_size: int = 64
    learning_rate: float = 2e-4  # LoRA needs higher LR (20-100x)
    max_length: int = 8192       # traces are ~2K chars median, 8K tokens is plenty
    lora_rank: int = 32
    num_epochs: int = 1          # 1 epoch over 7.1K traces = 111 steps (was 2 epochs over 1K = 31 steps)
    save_every: int = 20
    eval_fraction: float = 0.1   # hold out 10% for validation


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------


def main(config: Config):
    if not config.data_path:
        raise ValueError("--data_path is required. Point to your *_sft.jsonl file.")

    # Setup logging
    ml_logger = ml_log.setup_logging(
        log_dir=config.log_path,
        wandb_project=None,
        wandb_name=None,
        config=config,
        do_configure_logging_module=True,
    )

    # Get tokenizer and renderer for Qwen3
    tokenizer = get_tokenizer(MODEL_NAME)
    renderer_name = model_info.get_recommended_renderer_name(MODEL_NAME)
    renderer = renderers.get_renderer(renderer_name, tokenizer)
    logger.info("Model: %s, Renderer: %s", MODEL_NAME, renderer_name)

    # Load data
    logger.info("Loading SFT data from %s", config.data_path)
    all_conversations = load_sft_data(config.data_path)
    logger.info("Loaded %d conversations", len(all_conversations))

    # Train/eval split
    n_eval = max(1, int(len(all_conversations) * config.eval_fraction))
    eval_conversations = all_conversations[:n_eval]
    train_conversations = all_conversations[n_eval:]
    logger.info("Train: %d, Eval: %d", len(train_conversations), len(eval_conversations))

    # Convert eval set to datums (done once)
    eval_datums = [
        conversation_to_datum(
            conv, renderer, config.max_length,
            renderers.TrainOnWhat.ALL_ASSISTANT_MESSAGES,
        )
        for conv in eval_conversations
    ]
    logger.info("Eval datums prepared: %d", len(eval_datums))

    # Training setup
    n_train_batches_per_epoch = len(train_conversations) // config.batch_size
    n_total_steps = n_train_batches_per_epoch * config.num_epochs
    # Drop incomplete last batch
    n_dropped = len(train_conversations) % config.batch_size
    if n_dropped:
        logger.info("Dropping last %d examples per epoch (batch_size=%d)",
                     n_dropped, config.batch_size)
    logger.info("Steps per epoch: %d, Total steps: %d", n_train_batches_per_epoch, n_total_steps)

    # Create training client
    service_client = tinker.ServiceClient(base_url=config.base_url)

    resume_info = checkpoint_utils.get_last_checkpoint(config.log_path)
    if resume_info:
        # SDK 1.x returns a dict; older versions returned an object. Normalise.
        info = resume_info if isinstance(resume_info, dict) else vars(resume_info)
        training_client = service_client.create_training_client_from_state_with_optimizer(
            info["state_path"]
        )
        start_step = info["batch"]
        logger.info("Resuming from step %d", start_step)
    else:
        training_client = service_client.create_lora_training_client(
            base_model=MODEL_NAME, rank=config.lora_rank
        )
        start_step = 0

    # Training loop
    import random
    rng = random.Random(42)

    global_step = 0
    for epoch in range(config.num_epochs):
        # Shuffle training data each epoch
        shuffled = list(train_conversations)
        rng.shuffle(shuffled)

        for batch_idx in range(n_train_batches_per_epoch):
            global_step = epoch * n_train_batches_per_epoch + batch_idx

            if global_step < start_step:
                continue

            start_time = time.time()
            metrics = {}

            # Checkpoint
            if config.save_every > 0 and global_step % config.save_every == 0 and global_step > 0:
                checkpoint_utils.save_checkpoint(
                    training_client=training_client,
                    name=f"{global_step:06d}",
                    log_path=config.log_path,
                    kind="state",
                    loop_state={"batch": global_step},
                )

            # Linear LR schedule
            lr_mult = max(0.0, 1.0 - global_step / n_total_steps)
            current_lr = config.learning_rate * lr_mult
            adam_params = tinker.AdamParams(
                learning_rate=current_lr, beta1=0.9, beta2=0.95, eps=1e-8
            )

            # Build batch
            batch_start = batch_idx * config.batch_size
            batch_end = batch_start + config.batch_size
            batch_convs = shuffled[batch_start:batch_end]

            batch = [
                conversation_to_datum(
                    conv, renderer, config.max_length,
                    renderers.TrainOnWhat.ALL_ASSISTANT_MESSAGES,
                )
                for conv in batch_convs
            ]

            # Forward-backward + optimizer step
            fwd_bwd_future = training_client.forward_backward(batch, loss_fn="cross_entropy")
            optim_step_future = training_client.optim_step(adam_params)

            fwd_bwd_result = fwd_bwd_future.result()
            optim_result = optim_step_future.result()

            if optim_result.metrics:
                metrics.update(optim_result.metrics)

            # Train NLL
            train_logprobs = [x["logprobs"] for x in fwd_bwd_result.loss_fn_outputs]
            train_weights = [d.loss_fn_inputs["weights"] for d in batch]
            train_nll = compute_mean_nll(train_logprobs, train_weights)

            # Eval NLL (every 10 steps)
            if global_step % 10 == 0:
                eval_fwd = training_client.forward_backward(
                    eval_datums, loss_fn="cross_entropy"
                )
                eval_result = eval_fwd.result()
                eval_logprobs = [x["logprobs"] for x in eval_result.loss_fn_outputs]
                eval_weights = [d.loss_fn_inputs["weights"] for d in eval_datums]
                eval_nll = compute_mean_nll(eval_logprobs, eval_weights)
                metrics["eval_mean_nll"] = eval_nll

            metrics.update(
                epoch=epoch,
                num_sequences=len(batch),
                num_tokens=sum(d.model_input.length for d in batch),
                learning_rate=current_lr,
                train_mean_nll=train_nll,
                progress=global_step / n_total_steps,
                time_total=time.time() - start_time,
            )
            ml_logger.log_metrics(metrics=metrics, step=global_step)

    # Save final checkpoint
    checkpoint_utils.save_checkpoint(
        training_client=training_client,
        name="final",
        log_path=config.log_path,
        kind="both",
        loop_state={"batch": n_total_steps},
    )

    logger.info("Training completed! Final checkpoint saved.")
    logger.info("To evaluate, run: python scripts/tinker_eval.py --checkpoint %s",
                config.log_path)

    ml_logger.close()


if __name__ == "__main__":
    chz.nested_entrypoint(main)
